server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: producer-lna-service
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.demo.producerlna: DEBUG
